### ISSUE TITLE
Cannot find namespace 'NodeJS' when importing heart-ping

### ISSUE THREAD

**Issue by zuparnowa** [nicolaspearson/node.heart.ping#1]
I am having trouble using this module in my ionic 3 app.

All I have done so far is "npm i heart-ping --save", and then attempted to import into into the HomePage that is generated when starting a blank ionic project.

I am getting the error in the title of this post. It seems to be complaining about NodeJS.timer.

**Comment by nicolaspearson** [comment]
You are missing the types for node, i.e. `npm install --save @types/node`
